//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Latex.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LatexParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILatexVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] LatexParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] LatexParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.addition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddition([NotNull] LatexParser.AdditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.multiplication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplication([NotNull] LatexParser.MultiplicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary([NotNull] LatexParser.UnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.unarysufix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnarysufix([NotNull] LatexParser.UnarysufixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuffix([NotNull] LatexParser.SuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower([NotNull] LatexParser.PowerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.power_nofunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower_nofunc([NotNull] LatexParser.Power_nofuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] LatexParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.atom_nofunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom_nofunc([NotNull] LatexParser.Atom_nofuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] LatexParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.func_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_args([NotNull] LatexParser.Func_argsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.abs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbs([NotNull] LatexParser.AbsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.intfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntfunc([NotNull] LatexParser.IntfuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.frac"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrac([NotNull] LatexParser.FracContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.sqrt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSqrt([NotNull] LatexParser.SqrtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.subexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubexpr([NotNull] LatexParser.SubexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.supexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupexpr([NotNull] LatexParser.SupexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.parenthesis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesis([NotNull] LatexParser.ParenthesisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] LatexParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] LatexParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.letter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetter([NotNull] LatexParser.LetterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.mul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMul([NotNull] LatexParser.MulContext context);
}
