//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Latex.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LatexParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILatexVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet([NotNull] LatexParser.SetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.unions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnions([NotNull] LatexParser.UnionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.intersections"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntersections([NotNull] LatexParser.IntersectionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.differences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDifferences([NotNull] LatexParser.DifferencesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.set_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_atom([NotNull] LatexParser.Set_atomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.finite_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinite_set([NotNull] LatexParser.Finite_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.number_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_set([NotNull] LatexParser.Number_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.conditionnal_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionnal_set([NotNull] LatexParser.Conditionnal_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.parenthesis_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesis_set([NotNull] LatexParser.Parenthesis_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] LatexParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] LatexParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr([NotNull] LatexParser.OrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd([NotNull] LatexParser.AndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.not"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot([NotNull] LatexParser.NotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.cond_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCond_atom([NotNull] LatexParser.Cond_atomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.bool_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_value([NotNull] LatexParser.Bool_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.relationnal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationnal([NotNull] LatexParser.RelationnalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.in_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_set([NotNull] LatexParser.In_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.parenthesis_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesis_cond([NotNull] LatexParser.Parenthesis_condContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] LatexParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.addition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddition([NotNull] LatexParser.AdditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.multiplication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplication([NotNull] LatexParser.MultiplicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary([NotNull] LatexParser.UnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.unarysufix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnarysufix([NotNull] LatexParser.UnarysufixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuffix([NotNull] LatexParser.SuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower([NotNull] LatexParser.PowerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.power_nofunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower_nofunc([NotNull] LatexParser.Power_nofuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] LatexParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.atom_nofunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom_nofunc([NotNull] LatexParser.Atom_nofuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] LatexParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.func_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_args([NotNull] LatexParser.Func_argsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.abs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbs([NotNull] LatexParser.AbsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.intfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntfunc([NotNull] LatexParser.IntfuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.frac"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrac([NotNull] LatexParser.FracContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.sqrt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSqrt([NotNull] LatexParser.SqrtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.subexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubexpr([NotNull] LatexParser.SubexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.supexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupexpr([NotNull] LatexParser.SupexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.parenthesis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesis([NotNull] LatexParser.ParenthesisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] LatexParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] LatexParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.letter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetter([NotNull] LatexParser.LetterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LatexParser.mul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMul([NotNull] LatexParser.MulContext context);
}
