//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from myGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="myGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ImyGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] myGrammarParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] myGrammarParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] myGrammarParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] myGrammarParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.addition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddition([NotNull] myGrammarParser.AdditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.addition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddition([NotNull] myGrammarParser.AdditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.multiplication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplication([NotNull] myGrammarParser.MultiplicationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.multiplication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplication([NotNull] myGrammarParser.MultiplicationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary([NotNull] myGrammarParser.UnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary([NotNull] myGrammarParser.UnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.unarysufix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnarysufix([NotNull] myGrammarParser.UnarysufixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.unarysufix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnarysufix([NotNull] myGrammarParser.UnarysufixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuffix([NotNull] myGrammarParser.SuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuffix([NotNull] myGrammarParser.SuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPower([NotNull] myGrammarParser.PowerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPower([NotNull] myGrammarParser.PowerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.power_nofunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPower_nofunc([NotNull] myGrammarParser.Power_nofuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.power_nofunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPower_nofunc([NotNull] myGrammarParser.Power_nofuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] myGrammarParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] myGrammarParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.atom_nofunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom_nofunc([NotNull] myGrammarParser.Atom_nofuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.atom_nofunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom_nofunc([NotNull] myGrammarParser.Atom_nofuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] myGrammarParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] myGrammarParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.func_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_args([NotNull] myGrammarParser.Func_argsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.func_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_args([NotNull] myGrammarParser.Func_argsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.abs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbs([NotNull] myGrammarParser.AbsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.abs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbs([NotNull] myGrammarParser.AbsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.intfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntfunc([NotNull] myGrammarParser.IntfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.intfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntfunc([NotNull] myGrammarParser.IntfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.frac"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFrac([NotNull] myGrammarParser.FracContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.frac"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFrac([NotNull] myGrammarParser.FracContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.sqrt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSqrt([NotNull] myGrammarParser.SqrtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.sqrt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSqrt([NotNull] myGrammarParser.SqrtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.subexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubexpr([NotNull] myGrammarParser.SubexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.subexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubexpr([NotNull] myGrammarParser.SubexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.supexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSupexpr([NotNull] myGrammarParser.SupexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.supexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSupexpr([NotNull] myGrammarParser.SupexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.parenthesis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesis([NotNull] myGrammarParser.ParenthesisContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.parenthesis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesis([NotNull] myGrammarParser.ParenthesisContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] myGrammarParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] myGrammarParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] myGrammarParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] myGrammarParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.letter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetter([NotNull] myGrammarParser.LetterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.letter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetter([NotNull] myGrammarParser.LetterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myGrammarParser.mul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMul([NotNull] myGrammarParser.MulContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myGrammarParser.mul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMul([NotNull] myGrammarParser.MulContext context);
}
